name: Deploy
on:
  pull_request:
    types:
      - closed
  push:
jobs:
  if_merged:
    if: github.event.pull_request.merged == true || true
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: yarn install, build
      run: |
        yarn install
        yarn build
    - name: show
      run: |
        ls -l ./dist/*
