name: Deploy
on:
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: yarn install, build
      run: |
        yarn install
        yarn build
    - name: push to release　branch
      run: |
        ls -l ./dist/*
        mv ./dist /tmp/
        cd /tmp/dist/
        git init
        git remote add origin git@github.com:w-haibara/portfolio
        git checkout -b release
        git add .
        git commit -m update
        git push origin release -f
