name: Deploy
on:
  repository_dispatch:
    types: [prod]
  pull_request:
    branches: [main]
    types:
      - closed
jobs:
  if_merged:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: update content.json
      run: |
        curl -H "X-MICROCMS-API-KEY: ${{secrets.MICROCMS_API_KEY}}" https://w-haibara.microcms.io/api/v1/portfolio > ./src/content.json
    - name: yarn install, build
      run: |
        yarn install
        yarn build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: w-haibara.com
